version: '3'

services:
  web:
    image: nginx:alpine
    container_name: rikkileajames-web
    network_mode: bridge
    links:
      - cms
      - ssg
    environment:
      VIRTUAL_HOST: local.rikkileajames.com
    volumes:
      - ./web/config/nginx.conf:/etc/nginx/conf.d/custom.conf
      - ./web/dist:/opt/web
  cms:
    image: ghost:3-alpine
    container_name: rikkileajames-cms
    hostname: ghost
    network_mode: bridge
    environment:
      NODE_ENV: development
      url: http://local.rikkileajames.com
      mail__transport: SMTP
      mail__from: noreply@rikkileajames.com
      mail__options__host: ${SMTP_HOST}
      mail__options__port: ${SMTP_PORT}
      mail__options__auth__user: ${SMTP_USER}
      mail__options__auth__pass: ${SMTP_PASSWORD}
      mail__options__secureConnection: 'true'
  ssg:
    build:
      context: ./web
    container_name: rikkileajames-ssg
    hostname: nuxt
    network_mode: bridge
    environment:
      GHOST_API_URL: http://ghost:2368
      GHOST_API_KEY: ${GHOST_API_KEY}
    volumes:
      - ./web:/opt/web
    ports:
      - 3000:3000
