version: '3'

volumes:
  site:

services:
  web:
    build:
      context: ./web
    container_name: rikkileajames-web
    network_mode: bridge
    links:
      - cms
      - ssg
    environment:
      VIRTUAL_HOST: local.rikkileajames.com
    volumes:
      - site:/opt/site:ro
  cms:
    build:
      context: ./cms
    container_name: rikkileajames-cms
    hostname: ghost
    network_mode: bridge
    environment:
      NODE_ENV: development
      url: http://local.rikkileajames.com
      mail__transport: SMTP
      mail__from: noreply@rikkileajames.com
      mail__options__host: ${SMTP_HOST}
      mail__options__port: ${SMTP_PORT}
      mail__options__auth__user: ${SMTP_USER}
      mail__options__auth__pass: ${SMTP_PASSWORD}
      mail__options__secureConnection: 'true'
    volumes:
      - ./cms/data/data:/var/lib/ghost/content/data
      - ./cms/data/images:/var/lib/ghost/content/images
  ssg:
    build:
      context: ./ssg
    container_name: rikkileajames-ssg
    hostname: nuxt
    links:
      - cms
    network_mode: bridge
    environment:
      GHOST_API_URL: http://ghost:2368
      GHOST_API_KEY: ${GHOST_API_KEY}
    volumes:
      - ./ssg:/opt/ssg
      - site:/opt/site
    ports:
      - 3000:3000
