version: '3'

services:
  cms:
    image: ghost
    container_name: rikkileajames-cms
    hostname: ghost
    network_mode: bridge
    environment:
      url: http://local.rikkileajames.com
  web:
    build:
      context: ./web
    container_name: rikkileajames-web
    network_mode: bridge
    links:
      - cms
    environment:
      VIRTUAL_HOST: local.rikkileajames.com
      GHOST_API_URL: http://ghost/ghost/api/v2
