version: '3'

volumes:
  site:

networks:
  front:
    external:
      name: proxy
  back:

services:
  web:
    build:
      context: ./web
    container_name: rikkileajames-web
    networks:
      - front
      - back
    environment:
      VIRTUAL_HOST: local.rikkileajames.com
    volumes:
      - site:/opt/site:ro
  cms:
    build:
      context: ./cms
    container_name: rikkileajames-cms
    networks:
      - back
    environment:
      NODE_ENV: development
      url: http://local.rikkileajames.com
      mail__transport: SMTP
      mail__from: noreply@rikkileajames.com
      mail__options__host: ${SMTP_HOST}
      mail__options__port: ${SMTP_PORT}
      mail__options__auth__user: ${SMTP_USER}
      mail__options__auth__pass: ${SMTP_PASSWORD}
      mail__options__secureConnection: 'true'
    volumes:
      - ./cms/data/data:/var/lib/ghost/content/data
      - ./cms/data/images:/var/lib/ghost/content/images
  ssg:
    build:
      context: ./ssg
    container_name: rikkileajames-ssg
    networks:
      back:
        aliases:
          - ssg.backend
    environment:
      GHOST_API_URL: http://cms:2368
      GHOST_API_KEY: ${GHOST_API_KEY}
    volumes:
      - ./ssg:/opt/ssg
      - site:/opt/site
    ports:
      - 3000:3000
